export type InspirationFooterDetailType = {
  name: string;
  detail: string;
};
export type InspirationFooterType = {
  Popular: InspirationFooterDetailType[];
  "Arts & culture": InspirationFooterDetailType[];
  "Out doors": InspirationFooterDetailType[];
  Mountains: InspirationFooterDetailType[];
  Beach: InspirationFooterDetailType[];
  "Unique stays": InspirationFooterDetailType[];
  Categories: InspirationFooterDetailType[];
  "Things to do": InspirationFooterDetailType[];
  "Travel tips & inspiration": InspirationFooterDetailType[];
  "Airbnb-friendly apartment": InspirationFooterDetailType[];
};
export const inspiration: InspirationFooterType = {
  Popular: [
    { name: "Canmore", detail: "Condo rentals" },
    { name: "Benalmádena", detail: "Apartment rentals" },
    { name: "Marbella", detail: "Vacation rentals" },
    { name: "Mijas", detail: "Vacation rentals" },
    { name: "Prescott", detail: "Cabin rentals" },
    { name: "Scottsdale", detail: "Vacation rentals" },
    { name: "Tucson", detail: "Vacation rentals" },
    { name: "Jasper", detail: "Cabin rentals" },
    { name: "Mountain View", detail: "Cabin rentals" },
    { name: "Devonport", detail: "Cottage rentals" },
    { name: "Mallacoota", detail: "Pet-friendly rentals" },
    { name: "Ibiza", detail: "Apartment rentals" },
  ],
  "Arts & culture": [
    { name: "Canmore", detail: "Condo rentals" },
    { name: "Benalmádena", detail: "Apartment rentals" },
    { name: "Marbella", detail: "Vacation rentals" },
    { name: "Mijas", detail: "Vacation rentals" },
    { name: "Prescott", detail: "Cabin rentals" },
    { name: "Scottsdale", detail: "Vacation rentals" },
    { name: "Tucson", detail: "Vacation rentals" },
    { name: "Jasper", detail: "Cabin rentals" },
    { name: "Mountain View", detail: "Cabin rentals" },
    { name: "Devonport", detail: "Cottage rentals" },
    { name: "Mallacoota", detail: "Pet-friendly rentals" },
    { name: "Ibiza", detail: "Apartment rentals" },
  ],
  "Out doors": [
    { name: "Canmore", detail: "Condo rentals" },
    { name: "Benalmádena", detail: "Apartment rentals" },
    { name: "Marbella", detail: "Vacation rentals" },
    { name: "Mijas", detail: "Vacation rentals" },
    { name: "Prescott", detail: "Cabin rentals" },
    { name: "Scottsdale", detail: "Vacation rentals" },
    { name: "Tucson", detail: "Vacation rentals" },
    { name: "Jasper", detail: "Cabin rentals" },
    { name: "Mountain View", detail: "Cabin rentals" },
    { name: "Devonport", detail: "Cottage rentals" },
    { name: "Mallacoota", detail: "Pet-friendly rentals" },
    { name: "Ibiza", detail: "Apartment rentals" },
  ],
  Mountains: [
    { name: "Canmore", detail: "Condo rentals" },
    { name: "Benalmádena", detail: "Apartment rentals" },
    { name: "Marbella", detail: "Vacation rentals" },
    { name: "Mijas", detail: "Vacation rentals" },
    { name: "Prescott", detail: "Cabin rentals" },
    { name: "Scottsdale", detail: "Vacation rentals" },
    { name: "Tucson", detail: "Vacation rentals" },
    { name: "Jasper", detail: "Cabin rentals" },
    { name: "Mountain View", detail: "Cabin rentals" },
    { name: "Devonport", detail: "Cottage rentals" },
    { name: "Mallacoota", detail: "Pet-friendly rentals" },
    { name: "Ibiza", detail: "Apartment rentals" },
  ],
  Beach: [
    { name: "Canmore", detail: "Condo rentals" },
    { name: "Benalmádena", detail: "Apartment rentals" },
    { name: "Marbella", detail: "Vacation rentals" },
    { name: "Mijas", detail: "Vacation rentals" },
    { name: "Prescott", detail: "Cabin rentals" },
    { name: "Scottsdale", detail: "Vacation rentals" },
    { name: "Tucson", detail: "Vacation rentals" },
    { name: "Jasper", detail: "Cabin rentals" },
    { name: "Mountain View", detail: "Cabin rentals" },
    { name: "Devonport", detail: "Cottage rentals" },
    { name: "Mallacoota", detail: "Pet-friendly rentals" },
    { name: "Ibiza", detail: "Apartment rentals" },
  ],
  "Unique stays": [
    { name: "Canmore", detail: "Condo rentals" },
    { name: "Benalmádena", detail: "Apartment rentals" },
    { name: "Marbella", detail: "Vacation rentals" },
    { name: "Mijas", detail: "Vacation rentals" },
    { name: "Prescott", detail: "Cabin rentals" },
    { name: "Scottsdale", detail: "Vacation rentals" },
    { name: "Tucson", detail: "Vacation rentals" },
    { name: "Jasper", detail: "Cabin rentals" },
    { name: "Mountain View", detail: "Cabin rentals" },
    { name: "Devonport", detail: "Cottage rentals" },
    { name: "Mallacoota", detail: "Pet-friendly rentals" },
    { name: "Ibiza", detail: "Apartment rentals" },
  ],
  Categories: [
    { name: "Canmore", detail: "Condo rentals" },
    { name: "Benalmádena", detail: "Apartment rentals" },
    { name: "Marbella", detail: "Vacation rentals" },
    { name: "Mijas", detail: "Vacation rentals" },
    { name: "Prescott", detail: "Cabin rentals" },
    { name: "Scottsdale", detail: "Vacation rentals" },
    { name: "Tucson", detail: "Vacation rentals" },
    { name: "Jasper", detail: "Cabin rentals" },
    { name: "Mountain View", detail: "Cabin rentals" },
    { name: "Devonport", detail: "Cottage rentals" },
    { name: "Mallacoota", detail: "Pet-friendly rentals" },
    { name: "Ibiza", detail: "Apartment rentals" },
  ],
  "Things to do": [
    { name: "Canmore", detail: "Condo rentals" },
    { name: "Benalmádena", detail: "Apartment rentals" },
    { name: "Marbella", detail: "Vacation rentals" },
    { name: "Mijas", detail: "Vacation rentals" },
    { name: "Prescott", detail: "Cabin rentals" },
    { name: "Scottsdale", detail: "Vacation rentals" },
    { name: "Tucson", detail: "Vacation rentals" },
    { name: "Jasper", detail: "Cabin rentals" },
    { name: "Mountain View", detail: "Cabin rentals" },
    { name: "Devonport", detail: "Cottage rentals" },
    { name: "Mallacoota", detail: "Pet-friendly rentals" },
    { name: "Ibiza", detail: "Apartment rentals" },
  ],
  "Travel tips & inspiration": [
    { name: "Canmore", detail: "Condo rentals" },
    { name: "Benalmádena", detail: "Apartment rentals" },
    { name: "Marbella", detail: "Vacation rentals" },
    { name: "Mijas", detail: "Vacation rentals" },
    { name: "Prescott", detail: "Cabin rentals" },
    { name: "Scottsdale", detail: "Vacation rentals" },
    { name: "Tucson", detail: "Vacation rentals" },
    { name: "Jasper", detail: "Cabin rentals" },
    { name: "Mountain View", detail: "Cabin rentals" },
    { name: "Devonport", detail: "Cottage rentals" },
    { name: "Mallacoota", detail: "Pet-friendly rentals" },
    { name: "Ibiza", detail: "Apartment rentals" },
  ],
  "Airbnb-friendly apartment": [
    { name: "Canmore", detail: "Condo rentals" },
    { name: "Benalmádena", detail: "Apartment rentals" },
    { name: "Marbella", detail: "Vacation rentals" },
    { name: "Mijas", detail: "Vacation rentals" },
    { name: "Prescott", detail: "Cabin rentals" },
    { name: "Scottsdale", detail: "Vacation rentals" },
    { name: "Tucson", detail: "Vacation rentals" },
    { name: "Jasper", detail: "Cabin rentals" },
    { name: "Mountain View", detail: "Cabin rentals" },
    { name: "Devonport", detail: "Cottage rentals" },
    { name: "Mallacoota", detail: "Pet-friendly rentals" },
    { name: "Ibiza", detail: "Apartment rentals" },
  ],
};
